### ISSUE TITLE
Add instructions on how to build this for alternate architectures

### ISSUE THREAD

**Issue by RichardBronosky** [crccheck/docker-hello-world#7]
I love that you based this off of https://hub.docker.com/_/busybox/ because it supports so many architectures. I want to use this image as the base for a Raspberry Pi Kubernetes tutorial I am building. Unfortunately, following your README will result is a unexecutable binary failure. It's easy to work around. I simply did:

```
# Note: this is a pattern that can be used for many containers, not just this one
url=https://github.com/crccheck/docker-hello-world
image=$(basename $url)
git clone $url
cd $image
docker build -t $image .
docker run -d --name web-test -p 80:8000 $image
docker ps
curl localhost:80
```

For most projects I'd say that knowing how to build from source is the user's responsibility. However, this is a hello-world, and that suggests a different kind of user. I think an extra paragraph in the README is in order.

You might also go so far as to push an ARM build out to the registry, but I don't want to ask for heroics. ;-)

**Comment by crccheck** [comment]
This repo could use some love in other areas too. I put it on my big TODO list. Maybe with the extra hour I get this weekend.

**Comment by crccheck** [comment]
I tried to incorporate this into #12 , but even though this is a hello world, I didn't want to get into maintaining all the different ways to do the dev flow for Docker images quite yet.
